export const mons = [
  {
    mid: 1,
    sid: 0,
    name: 'フシギダネ',
    sexes: [1, 2],
    class: 1,
    types: [1, 2],
    height: 0.7,
    weight: 6.9,
    characteristics: [1],
    hp: 4,
    atk: 4,
    def: 4,
    satk: 5,
    sdef: 5,
    agi: 4,
    descriptions: [
      'うまれたときから　せなかに　しょくぶつの　タネが　あって　すこしずつ　おおきく　そだつ。　（『ポケモン ソード』より）',
      'うまれて　しばらくの　あいだ　せなかの　タネに　つまった　えいようを　とって　そだつ。　（『ポケモン シールド』より）',
    ],
    evolutions: [1, 2, 3],
    anotherStyles: [],
  },
  {
    mid: 2,
    sid: 0,
    name: 'フシギソウ',
    sexes: [1, 2],
    class: 1,
    types: [1, 2],
    height: 1.0,
    weight: 13.0,
    characteristics: [1],
    hp: 4,
    atk: 4,
    def: 4,
    satk: 5,
    sdef: 5,
    agi: 4,
    descriptions: [
      'せなかの　つぼみが　おおきく　そだってくると　２ほんあしで　たつことが　できなくなるらしい。　（『ポケモン ソード』より）',
      'たいようの　ひかりを　あびるほど　からだに　ちからが　わいて　せなかの　つぼみが　そだっていく。　（『ポケモン シールド』より）',
    ],
    evolutions: [1, 2, 3],
    anotherStyles: [],
  },
  {
    mid: 3,
    sid: 0,
    name: 'フシギバナ',
    sexes: [1, 2],
    class: 1,
    types: [1, 2],
    height: 2.0,
    weight: 100.0,
    characteristics: [1],
    hp: 5,
    atk: 5,
    def: 5,
    satk: 6,
    sdef: 6,
    agi: 5,
    descriptions: [
      'たいようエネルギーを　えいようにして　おおきなハナが　ひらく。　ひなたに　ひきよせられるように　いどうする。　（『ポケモン ソード』より）',
      'はなから　うっとりする　かおりが　ただよい　たたかうものの　きもちを　なだめてしまう。　（『ポケモン シールド』より）',
    ],
    evolutions: [1, 2, 3],
    anotherStyles: [0, 1, 2],
  },
  {
    mid: 3,
    sid: 1,
    name: 'メガフシギバナ',
    sexes: [1, 2],
    class: 1,
    types: [1, 2],
    height: 2.4,
    weight: 155.5,
    characteristics: [2],
    hp: 5,
    atk: 6,
    def: 8,
    satk: 8,
    sdef: 8,
    agi: 5,
    descriptions: [
      'おおきな　はなびらを　ひろげたいようの　ひかりを　あびているとからだに　げんきが　みなぎっていく。　（『ポケモン Ｘ』より）',
      'あめの　ふった　よくじつは　せなかのはなの　かおりが　つよまる。　かおりにさそわれ　ポケモンが　あつまる。　（『ポケモン Ｙ』より）',
    ],
    evolutions: [1, 2, 3],
    anotherStyles: [0, 1, 2],
  },
  {
    mid: 3,
    sid: 2,
    name: 'フシギバナ',
    sname: 'キョダイマックスのすがた',
    sexes: [1, 2],
    class: 0,
    types: [1, 2],
    height: 24.0,
    weight: -1,
    characteristics: [1],
    hp: 5,
    atk: 5,
    def: 5,
    satk: 6,
    sdef: 6,
    agi: 5,
    descriptions: [
      '２ほんの　ふとい　ツルを　ふりまわし　たたかう。　１０かいだての　ビルを　かるく　なぎたおすほど　パワフルだ。　（『ポケモン ソード』より）',
      'やまの　ふんかのような　いきおいで　ばらまく　たいりょうの　かふんは　すいこみすぎると　きを　うしなうぞ。　（『ポケモン シールド』より）',
    ],
    evolutions: [1, 2, 3],
    anotherStyles: [0, 1, 2],
  },
  {
    mid: 4,
    sid: 0,
    name: 'ヒトカゲ',
    sexes: [1, 2],
    class: 2,
    types: [3],
    height: 0.6,
    weight: 8.5,
    characteristics: [3],
    hp: 3,
    atk: 4,
    def: 3,
    satk: 4,
    sdef: 3,
    agi: 4,
    descriptions: [
      'あついものを　このむ　せいかく。　あめにぬれると　しっぽの　さきから　けむりが　でるという。　（『ポケモン ソード』より）',
      'うまれたときから　しっぽに　ほのおが　ともっている。　ほのおが　きえたとき　その　いのちは　おわって　しまう。　（『ポケモン シールド』より）',
    ],
    evolutions: [4, 5, 6],
    anotherStyles: [],
  },
  {
    mid: 5,
    sid: 0,
    name: 'リザード',
    sexes: [1, 2],
    class: 3,
    types: [3],
    height: 1.1,
    weight: 19.0,
    characteristics: [3],
    hp: 4,
    atk: 4,
    def: 4,
    satk: 5,
    sdef: 4,
    agi: 5,
    descriptions: [
      'もえる　しっぽを　ふりまわし　するどい　ツメで　あいてを　きりさく　あらあらしい　せいかく。　（『ポケモン ソード』より）',
      'たたかいで　きもちが　たかぶると　しゃくねつの　ほのおを　ふきながら　あたりを　もやしてまわる。　（『ポケモン シールド』より）',
    ],
    evolutions: [4, 5, 6],
    anotherStyles: [],
  },
  {
    mid: 6,
    sid: 0,
    name: 'リザードン',
    sexes: [1, 2],
    class: 3,
    types: [3, 4],
    height: 1.7,
    weight: 90.5,
    characteristics: [3],
    hp: 5,
    atk: 5,
    def: 5,
    satk: 7,
    sdef: 5,
    agi: 6,
    descriptions: [
      'がんせきも　やけるような　しゃくねつの　ほのおを　はいて　やまかじを　おこすことが　ある。　（『ポケモン ソード』より）',
      'ちじょう　１４００メートル　まで　ハネを　つかって　とぶことができる。　こうねつの　ほのおを　はく。　（『ポケモン シールド』より）'
    ],
    evolutions: [4, 5, 6],
    anotherStyles: [0, 1, 2, 3],
  },
  {
    mid: 6,
    sid: 1,
    name: 'メガリザードンＸ',
    sexes: [1, 2],
    class: 3,
    types: [3, 5],
    height: 1.7,
    weight: 110.5,
    characteristics: [4],
    hp: 5,
    atk: 8,
    def: 7,
    satk: 8,
    sdef: 5,
    agi: 6,
    descriptions: [
      'くちから　しゃくねつの　ほのおをはきだすとき　しっぽの　さきはより　あかく　はげしく　もえあがる。　（『ポケモン Ｘ』より）',
      'ちじょう　１４００メートル　までハネを　つかって　とぶことができる。　こうねつの　ほのおを　はく。　（『ポケモン Ｙ』より）',
    ],
    evolutions: [4, 5, 6],
    anotherStyles: [0, 1, 2, 3],
  },
  {
    mid: 6,
    sid: 2,
    name: 'メガリザードンＹ',
    sexes: [1, 2],
    class: 3,
    types: [3, 4],
    height: 1.7,
    weight: 100.5,
    characteristics: [5],
    hp: 5,
    atk: 7,
    def: 5,
    satk: 10,
    sdef: 7,
    agi: 6,
    descriptions: [
      'くちから　しゃくねつの　ほのおをはきだすとき　しっぽの　さきはより　あかく　はげしく　もえあがる。　（『ポケモン Ｘ』より）',
      'ちじょう　１４００メートル　までハネを　つかって　とぶことができる。　こうねつの　ほのおを　はく。　（『ポケモン Ｙ』より）',
    ],
    evolutions: [4, 5, 6],
    anotherStyles: [0, 1, 2, 3],
  },
  {
    mid: 6,
    sid: 3,
    name: 'リザードン',
    sname: 'キョダイマックスのすがた',
    sexes: [1, 2],
    class: 0,
    types: [3, 4],
    height: 28.0,
    weight: -1,
    characteristics: [3],
    hp: 5,
    atk: 5,
    def: 5,
    satk: 7,
    sdef: 5,
    agi: 6,
    descriptions: [
      'キョダイマックスの　パワーによって　ほのおの　つばさを　もつ　きょだいな　リザードンの　すがたが　つくられた。　（『ポケモン ソード』より）',
      'せっし２０００どの　ほのおが　たいないで　うずまく。　ほえると　かりょくが　さらに　あがる。　（『ポケモン シールド』より）',
    ],
    evolutions: [4, 5, 6],
    anotherStyles: [0, 1, 2, 3],
  },
  {
    mid: 7,
    sid: 0,
    name: 'ゼニガメ',
    sexes: [1, 2],
    class: 4,
    types: [6],
    height: 0.5,
    weight: 9.0,
    characteristics: [6],
    hp: 3,
    atk: 3,
    def: 4,
    satk: 3,
    sdef: 4,
    agi: 3,
    descriptions: [
      'ながい　くびを　こうらのなかに　ひっこめるとき　いきおいよく　みずでっぽうを　はっしゃする。　（『ポケモン ソード』より）',
      'あぶなくなると　こうらに　てあしを　ひっこめて　みを　まもりながら　くちから　みずを　ふきだしてくる。　（『ポケモン シールド』より）',
    ],
    evolutions: [7, 8, 9],
    anotherStyles: [],
  },
  {
    mid: 8,
    sid: 0,
    name: 'カメール',
    sexes: [1, 2],
    class: 5,
    types: [6],
    height: 1.0,
    weight: 22.5,
    characteristics: [6],
    hp: 4,
    atk: 4,
    def: 5,
    satk: 4,
    sdef: 5,
    agi: 4,
    descriptions: [
      'ながいきの　シンボルと　されている。　こうらに　コケが　ついているのは　とくに　ながいきの　カメールだ。　（『ポケモン ソード』より）',
      'ふさふさの　みみと　しっぽを　たくみに　あやつって　すいちゅうでの　バランスを　たもつ。　（『ポケモン シールド』より）',
    ],
    evolutions: [7, 8, 9],
    anotherStyles: [],
  },
  {
    mid: 9,
    sid: 0,
    name: 'カメックス',
    sexes: [1, 2],
    class: 6,
    types: [6],
    height: 1.6,
    weight: 85.5,
    characteristics: [6],
    hp: 5,
    atk: 5,
    def: 6,
    satk: 5,
    sdef: 7,
    agi: 5,
    descriptions: [
      'からだが　おもたく　のしかかって　あいてを　きぜつさせる。　ピンチの　ときは　カラに　かくれる。　（『ポケモン ソード』より）',
      'こうらの　ロケットほう　から　ふきだした　ジェットすいりゅうは　ぶあつい　てっぱんも　つらぬく。　（『ポケモン シールド』より）',
    ],
    evolutions: [7, 8, 9],
    anotherStyles: [0, 1, 2],
  },
  {
    mid: 9,
    sid: 1,
    name: 'メガカメックス',
    sexes: [1, 2],
    class: 6,
    types: [6],
    height: 1.6,
    weight: 101.1,
    characteristics: [7],
    hp: 5,
    atk: 7,
    def: 8,
    satk: 8,
    sdef: 7,
    agi: 5,
    descriptions: [
      'からだが　おもたく　のしかかってあいてを　きぜつさせる。　ピンチの　ときは　カラに　かくれる。　（『ポケモン Ｘ』より）',
      'こうらに　ふんしゃこうが　あってロケットのような　いきおいでつっこんでくる　すごい　やつだ。　（『ポケモン Ｙ』より）',
    ],
    evolutions: [7, 8, 9],
    anotherStyles: [0, 1, 2],
  },
  {
    mid: 9,
    sid: 2,
    name: 'カメックス',
    sname: 'キョダイマックスのすがた',
    sexes: [1, 2],
    class: 0,
    types: [6],
    height: 25.0,
    weight: -1,
    characteristics: [6],
    hp: 5,
    atk: 5,
    def: 6,
    satk: 5,
    sdef: 7,
    agi: 5,
    descriptions: [
      'せいみつな　しゃげきは　ニガテ。　３１もんの　たいほうで　うってうって　うちまくる　スタイルで　せめるのだ。　（『ポケモン ソード』より）',
      'まんなかの　しゅほうから　はなたれる　みずでっぽうは　やまを　うちぬき　あなを　あける　はかいりょくだ。　（『ポケモン シールド』より）',
    ],
    evolutions: [7, 8, 9],
    anotherStyles: [0, 1, 2],
  },
]

export const sex = [
  {
    id: 0,
    name: '不明',
  },
  {
    id: 1,
    name: 'オス',
  },
  {
    id: 2,
    name: 'メス',
  },
]

export const clazz = [
  {
    id: 0,
    name: '-',
  },
  {
    id: 1,
    name: 'たねポケモン',
  },
  {
    id: 2,
    name: 'とかげポケモン',
  },
  {
    id: 3,
    name: 'かえんポケモン',
  },
  {
    id: 4,
    name: 'かめのこポケモン',
  },
  {
    id: 5,
    name: 'かめポケモン',
  },
  {
    id: 6,
    name: 'こうらポケモン',
  },
]

export const type = [
  {
    id: 0,
    name: 'ノーマル',
  },
  {
    id: 1,
    name: 'くさ',
  },
  {
    id: 2,
    name: 'どく',
  },
  {
    id: 3,
    name: 'ほのお',
  },
  {
    id: 4,
    name: 'ひこう',
  },
  {
    id: 5,
    name: 'ドラゴン',
  },
  {
    id: 6,
    name: 'みず',
  },
]

export const characteristic = [
  {
    id: 1,
    name: 'しんりょく',
    description: 'ＨＰが　へったとき　くさタイプの　わざの　いりょくが　あがる。',
  },
  {
    id: 2,
    name: 'あついしぼう',
    description: 'あつい　しぼうで　まもられているので　ほのおタイプと　こおりタイプの　わざの　ダメージを　はんげんさせる。',
  },
  {
    id: 3,
    name: 'もうか',
    description: 'ＨＰが　へったとき　ほのおタイプの　わざの　いりょくが　あがる。',
  },
  {
    id: 4,
    name: 'かたいツメ',
    description: 'あいてに　せっしょくする　わざの　いりょくが　たかくなる。',
  },
  {
    id: 5,
    name: 'ひでり',
    description: 'とうじょう　したときに　てんきを　はれに　する。',
  },
  {
    id: 6,
    name: 'げきりゅう',
    description: 'ＨＰが　へったとき　みずタイプの　わざの　いりょくが　あがる。',
  },
  {
    id: 7,
    name: 'メガランチャー',
    description: 'はどうの　わざのいりょくが　たかくなる。',
  },
]
